spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/otus
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

  sql:
    init:
      mode: always
      data-locations: data.sql
      #schema-locations: schema.sql